export const ICON_MAP: Record<string, string> = {
  // Transport
  uber: "Car",
  lyft: "Car",
  taxi: "Car",
  cab: "Car",
  bus: "Bus",
  train: "Train",
  flight: "Plane",
  plane: "Plane",
  airport: "Plane",
  fuel: "Fuel",
  gas: "Fuel",
  petrol: "Fuel",
  parking: "ParkingCircle",
  toll: "Coins",
  
  // Food & Drink
  groceries: "ShoppingBasket",
  grocery: "ShoppingBasket",
  supermarket: "ShoppingBasket",
  fruit: "Apple",
  vegetables: "Carrot",
  coffee: "Coffee",
  cafe: "Coffee",
  latte: "Coffee",
  espresso: "Coffee",
  starbucks: "Coffee",
  beer: "Beer",
  drink: "GlassWater", // or Beer/Wine
  alcohol: "Beer",
  wine: "Wine",
  burger: "Sandwich", 
  pizza: "Pizza",
  sushi: "Fish",
  fish: "Fish",
  steak: "Utensils",
  restaurant: "Utensils",
  dinner: "Utensils",
  lunch: "Utensils",
  breakfast: "Croissant",
  croissant: "Croissant",
  bakery: "Croissant",
  cake: "Cake",
  dessert: "IceCream",
  icecream: "IceCream",
  chocolate: "Candy",
  candy: "Candy",
  popcorn: "Popcorn",
  snack: "Popcorn",
  
  // Entertainment
  movie: "Film",
  cinema: "Film",
  film: "Film",
  game: "Gamepad2",
  steam: "Gamepad2",
  playstation: "Gamepad2",
  xbox: "Gamepad2",
  netflix: "Tv",
  tv: "Tv",
  hulu: "Tv",
  disney: "Tv",
  music: "Music",
  spotify: "Music",
  concert: "Mic2",
  party: "PartyPopper",
  ticket: "Ticket",
  
  // Health
  gym: "Dumbbell",
  workout: "Dumbbell",
  fitness: "Dumbbell",
  sport: "Trophy",
  yoga: "Activity",
  doctor: "Stethoscope",
  hospital: "Stethoscope",
  clinic: "Stethoscope",
  meds: "Pill",
  pill: "Pill",
  pharmacy: "Pill",
  dentist: "Smile", // or general health
  
  // Shopping / Bills
  shopping: "ShoppingBag",
  clothes: "Shirt",
  shirt: "Shirt",
  dress: "Shirt",
  shoes: "Footprints", // No Shoe icon in Lucide?
  sneakers: "Footprints", 
  internet: "Wifi",
  wifi: "Wifi",
  phone: "Phone",
  mobile: "Smartphone",
  bill: "Receipt",
  rent: "Home",
  utilities: "Zap",
  electricity: "Zap",
  water: "Droplets",
  subscription: "Repeat",
  
  // Tech
  laptop: "Laptop",
  computer: "Monitor",
  mouse: "Mouse",
  keyboard: "Keyboard",
  camera: "Camera",
  headphone: "Headphones",
  
  // Misc
  gift: "Gift",
  donation: "Heart",
  charity: "Heart",
  pet: "Dog",
  dog: "Dog",
  cat: "Cat",
  vet: "Stethoscope",
  baby: "Baby",
  book: "Book",
  education: "GraduationCap",
  course: "GraduationCap",
  haircut: "Scissors",
  salon: "Scissors",
};
